### ISSUE TITLE
Blaze issue

### ISSUE THREAD

**Issue by ShadowGaming100** [ShadowGaming100/Uptime#1]
Things caused the problem 

wrong settings in client or server
Incorrect url in variable 
Setup incorrect

**Comment by 1746705990** [comment]
ok let's continue

**Comment by ShadowGaming100** [comment]
I will create a Vercel project with your websocket

**Comment by 1746705990** [comment]
How about it? There seems to be something wrong with that link.

**Comment by ShadowGaming100** [comment]
> How about it? There seems to be something wrong with that link.

Maybe

**Comment by 1746705990** [comment]
However, replit cannot transfer files, even though the page is complete.

**Comment by 1746705990** [comment]
I'll give you the link to build with Replit, but it might take a few minutes.

**Comment by ShadowGaming100** [comment]
> However, replit cannot transfer files, even though the page is complete.

I have tested with replit and it works file

**Comment by ShadowGaming100** [comment]
> I'll give you the link to build with Replit, but it might take a few minutes.

Ok

**Comment by 1746705990** [comment]
Can it upload files under different networks?

**Comment by ShadowGaming100** [comment]
How are you hosting your website??

**Comment by ShadowGaming100** [comment]
https://blaze-sbq2.vercel.app/app/t/

**Comment by ShadowGaming100** [comment]
![84E21BA0-276F-44E3-BA0C-EB13193940D8](https://github.com/ShadowGaming100/Uptime/assets/81495140/3ed7fcc1-b1cd-4200-9d53-80d8af25252c)

@1746705990 


It worked for local network 

![67C5387A-6146-4320-BACA-71F8802E11CA](https://github.com/ShadowGaming100/Uptime/assets/81495140/6471ea2a-f197-41c0-9265-32a35fe999f5)

It worked for rooms even

**Comment by 1746705990** [comment]
Can it upload files under different networks?

**Comment by ShadowGaming100** [comment]
> https://blaze-sbq2.vercel.app/app/t/

Test it in your phone/computer

**Comment by ShadowGaming100** [comment]
> Can it upload files under different networks?

Yes

**Comment by 1746705990** [comment]
LAN is ok

**Comment by ShadowGaming100** [comment]
Mostly is not working because there has been a wrong settings in website or in server

**Comment by 1746705990** [comment]
![image](https://github.com/ShadowGaming100/Uptime/assets/126673150/94d8ded1-25fc-4d7f-b927-5e219a7f2b89)
This is the link to replit

**Comment by ShadowGaming100** [comment]
Ok

**Comment by ShadowGaming100** [comment]
In 2 minutes the website will use replit websocket

**Comment by ShadowGaming100** [comment]
https://blaze-sbq2.vercel.app/app/t/test



Here

**Comment by ShadowGaming100** [comment]
Connected saw you

**Comment by 1746705990** [comment]
Passed over

**Comment by ShadowGaming100** [comment]
Received file?

**Comment by 1746705990** [comment]
![image](https://github.com/ShadowGaming100/Uptime/assets/126673150/a4dc6685-638e-426b-939c-67292f21a316)

**Comment by ShadowGaming100** [comment]
Can I see the settings for the server maybe sometime is wrong with it 


Which hosting are you using for it??

**Comment by ShadowGaming100** [comment]
> ![image](https://user-images.githubusercontent.com/126673150/265230120-a4dc6685-638e-426b-939c-67292f21a316.png)

Works

**Comment by 1746705990** [comment]
Therefore, this Replit is no problem, but it is very slow.

**Comment by ShadowGaming100** [comment]
> Therefore, this Replit is no problem, but it is very slow.

Try local connection it will be faster

**Comment by 1746705990** [comment]
You mean, my cloud server?

**Comment by ShadowGaming100** [comment]
> You mean, my cloud server
> 
> Yes

Yes

**Comment by 1746705990** [comment]
Yes, local is very fast, but this has something to do with the bandwidth of the server.
![image](https://github.com/ShadowGaming100/Uptime/assets/126673150/ac8c3b7d-41ac-4c9e-b683-212bb9bf4e3d)

**Comment by 1746705990** [comment]
How about the speed when you use server instead of replit?

**Comment by ShadowGaming100** [comment]
> How about the speed when you use server instead of replit?

??

**Comment by 1746705990** [comment]
I seem to have misunderstood, you have been using replit.

**Comment by ShadowGaming100** [comment]
> I seem to have misunderstood, you have been using replit.

Yes

**Comment by 1746705990** [comment]
But I don't know where the problem is on the server side, although the logo of "{"message":"Blaze WebSockets running","rooms":0,"peers":0}" can appear.

**Comment by ShadowGaming100** [comment]
Can you show me the setup of the website

**Comment by ShadowGaming100** [comment]
Do you have node 16?? installed on the cloud server

**Comment by ShadowGaming100** [comment]
If yes I would like you to rebuild the website using npm install then npm run build

**Comment by 1746705990** [comment]
My server uses a cloud server, but the client still uses Vercel.

**Comment by ShadowGaming100** [comment]
Oh

**Comment by 1746705990** [comment]
![image](https://github.com/ShadowGaming100/Uptime/assets/126673150/5127d9c1-bb39-4386-a7c7-d98632dc7b33)
The server is node16

**Comment by ShadowGaming100** [comment]
Can you open the Vercel project and go to settings then project settings and show be Build & Development Settings and trot Directory

**Comment by 1746705990** [comment]
https://ablaze.daichenyang.me/app/t/hu

**Comment by 1746705990** [comment]
OK

**Comment by ShadowGaming100** [comment]
> https://ablaze.daichenyang.me/app/t/hu


??

**Comment by 1746705990** [comment]
This is built by the previous _cloud server_ + _replit_.

**Comment by ShadowGaming100** [comment]
Ok, is it to test it??

**Comment by ShadowGaming100** [comment]
Replit is down, If is down websocket won’t work

**Comment by 1746705990** [comment]
Yes, it disconnected and I opened another one.

**Comment by 1746705990** [comment]
![image](https://github.com/ShadowGaming100/Uptime/assets/126673150/f2120b0c-20e6-4a24-b44c-f38cbf8721b7)
Is this okay?

**Comment by ShadowGaming100** [comment]
In SERVER_HOST change http into https

if is http most of the browser like chrome blocks it

in install command 

override with npm install



Then redeploy

**Comment by ShadowGaming100** [comment]
> ![image](https://user-images.githubusercontent.com/126673150/265230827-f2120b0c-20e6-4a24-b44c-f38cbf8721b7.png)
> Is this okay?

Maybe that will fix all the issues you had

**Comment by 1746705990** [comment]
Okay, it's redeploying

**Comment by ShadowGaming100** [comment]
After you redeploy we will test it

**Comment by 1746705990** [comment]
Okay, thanks for the guidance, it may take a few more minutes.

**Comment by ShadowGaming100** [comment]
> Okay, thanks for the guidance, it may take a few more minutes.

No problem the longer it takes the better

**Comment by 1746705990** [comment]
[](https://replit-blaze.daichenyang.me/app/t/as)

**Comment by 1746705990** [comment]
https://replit-blaze.daichenyang.me/app/t/as

**Comment by 1746705990** [comment]
![Uploading image.png…]()
My computer still has no screen when I click it in, and my phone disconnects when I click it in.

**Comment by ShadowGaming100** [comment]
Show me the config

**Comment by ShadowGaming100** [comment]
vercel.com/teams/invite/JTX28klKocSUNTHmm9QdqDHHVRx4WU5M


join it and transfer the project to the team

I will try to see it

**Comment by 1746705990** [comment]
Hold on

**Comment by 1746705990** [comment]
You see what's wrong.

**Comment by ShadowGaming100** [comment]
Have you done any changes to blaze repository

**Comment by 1746705990** [comment]
No

**Comment by ShadowGaming100** [comment]
Because in Vercel shows deploy from follow changes

I disconnected your github repo and connected mine of blaze

**Comment by 1746705990** [comment]
You mean, the items it gives cannot be used directly, right?

**Comment by ShadowGaming100** [comment]
I cleared cache 
I double check the variable and now is deploying

**Comment by 1746705990** [comment]
How?

**Comment by ShadowGaming100** [comment]
> How?

??

**Comment by ShadowGaming100** [comment]
https://vercel.com/shadowgaming100-s-team/blaze/settings/data-cache

**Comment by 1746705990** [comment]
I mean, how you solve the problem is amazing.

**Comment by ShadowGaming100** [comment]
Can you refork the blaze repo then go to git click disconnect and click connect choose the repo and click connect

**Comment by ShadowGaming100** [comment]
> I mean, how you solve the problem is amazing.

It has something to do with cache

**Comment by ShadowGaming100** [comment]
Or wait delete the project and make a new one with the reforked one

**Comment by 1746705990** [comment]
I already did it, sorry

**Comment by ShadowGaming100** [comment]
No problem

**Comment by ShadowGaming100** [comment]
Now edit the the readme.me just add a dot or something so it will use that repo in future

**Comment by ShadowGaming100** [comment]
Now you can transfer back to your account

**Comment by 1746705990** [comment]
Okay, thanks for your help, it's almost dawn.

**Comment by ShadowGaming100** [comment]
> Okay, thanks for your help, it's almost dawn.

Welcome you can close the issue in blaze repo

**Comment by ShadowGaming100** [comment]
Issue solved

**Comment by ShadowGaming100** [comment]
@1746705990 better transfewithin 14 day otherwise the team will be deleted with repo

**Comment by 1746705990** [comment]
> @1746705990 better transfewithin 14 day otherwise the team will be deleted with repo

I have left the team and tried to redeploy myself, you can delete it, thank you again.

**Comment by ShadowGaming100** [comment]
On Sat, 2/09/2023 at 11:53 PM, Tomate ***@***.***> wrote:

> @1746705990 <https://github.com/1746705990> better transfewithin 14 day
> otherwise the team will be deleted with repo
>
> I have left the team and tried to redeploy myself, you can delete it,
> thank you again.
>

Ok, good night
One question do you know js and do you know how to code a Discord bot

**Comment by 1746705990** [comment]
> 

Nighty, I'm sorry that my major has nothing to do with this, so I don't know much about front-end related things.
